# configs/baseline.yaml
model_name: "meta-llama/Llama-3.2-1B"
lora_rank: 32
epochs: 1
learning_rate: 0.0002
save_steps: 50
log_steps: 10

# Dataset settings
dataset_name: "allenai/tulu-3-sft-olmo-2-mixture-0225"
max_samples: 100 # Change to null or remove this line when you want to run the full dataset