model_name: "meta-llama/Llama-3.2-1B"
lora_rank: 32
epochs: 1

# Training parameters
learning_rate: 0.00049
batch_size: 128
max_length: 4096
max_steps: 6758

# Checkpointing / logging
save_steps: 500
log_steps: 10
eval_steps: 0

# Dataset settings
dataset_name: "tulu3"

# Filtering settings
filter_min_assistant_tokens: 32
filter_max_assistant_tokens: 1024
dedup_exact: true